import { L10n, registerLicense } from '@syncfusion/ej2-base';

export const locale = {
    "pt-BR": {
      "grid": {
        "EmptyRecord": "Nenhum registro para exibir",
        "True": "Verdadeiro",
        "False": "Falso",
        "InvalidFilterMessage": "Dados de filtro inválidos",
        "GroupDropArea": "Arraste um cabeçalho de coluna aqui para agrupar pela coluna",
        "UnGroup": "Clique aqui para desagrupar",
        "GroupDisable": "Agrupamento desativado para esta coluna",
        "FilterbarTitle": "Célula de barra de filtro",
        "EmptyDataSourceError": "A fonte de dados não deve ser vazia no carregamento inicial, pois as colunas são geradas automaticamente da fonte de dados",
        "Add": "Adicionar",
        "Edit": "Editar",
        "Cancel": "Cancelar",
        "Update": "Atualizar",
        "Delete": "Excluir",
        "Print": "Imprimir",
        "Pdfexport": "Exportar para PDF",
        "Excelexport": "Exportar para Excel",
        "Wordexport": "Exportar para Word",
        "Csvexport": "Exportar para CSV",
        "Search": "Pesquisar",
        "Columnchooser": "Colunas",
        "Save": "Salvar",
        "Item": "registro",
        "Items": "registros",
        "EditOperationAlert": "Nenhum registro selecionado para editar",
        "DeleteOperationAlert": "Nenhum registro selecionado para excluir",
        "SaveButton": "Salvar",
        "OKButton": "OK",
        "CancelButton": "Cancelar",
        "EditFormTitle": "Detalhes de",
        "AddFormTitle": "Adicionar novo registro",
        "BatchSaveConfirm": "Deseja realmente salvar as alterações?",
        "BatchSaveLostChanges": "As alterações não salvas serão perdidas. Tem certeza de que deseja continuar?",
        "ConfirmDelete": "Tem certeza de que deseja excluir o registro?",
        "CancelEdit": "Tem certeza de que deseja cancelar as alterações?",
        "ChooseColumns": "Escolher colunas",
        "SearchColumns": "Pesquisar colunas",
        "Matchs": "Nenhum resultado encontrado",
        "FilterButton": "Filtrar",
        "ClearButton": "Limpar",
        "StartsWith": "Começa com",
        "EndsWith": "Termina com",
        "Contains": "Contém",
        "Equal": "Igual",
        "NotEqual": "Diferente",
        "LessThan": "Menor que",
        "LessThanOrEqual": "Menor ou igual a",
        "GreaterThan": "Maior que",
        "GreaterThanOrEqual": "Maior ou igual a",
        "ChooseDate": "Escolha uma data",
        "EnterValue": "Digite o valor",
        "Copy": "Copiar",
        "Group": "Agrupar por esta coluna",
        "Ungroup": "Desagrupar por esta coluna",
        "autoFitAll": "Ajustar todas as colunas automaticamente",
        "autoFit": "Ajustar esta coluna automaticamente",
        "Export": "Exportar",
        "FirstPage": "Primeira página",
        "LastPage": "Última página",
        "PreviousPage": "Página anterior",
        "NextPage": "Próxima página",
        "SortAscending": "Ordenar crescente",
        "SortDescending": "Ordenar decrescente",
        "EditRecord": "Editar registro",
        "DeleteRecord": "Excluir registro",
        "FilterMenu": "Filtro",
        "SelectAll": "Selecionar todos",
        "Blanks": "Em branco",
        "FilterTrue": "Verdadeiro",
        "FilterFalse": "Falso",
        "NoResult": "Nenhum resultado encontrado",
        "ClearFilter": "Limpar filtro",
        "NumberFilter": "Filtro de número",
        "TextFilter": "Filtro de texto",
        "DateFilter": "Filtro de data",
        "DateTimeFilter": "Filtro de data/hora",
        "MatchCase": "Diferenciar maiúsculas e minúsculas",
        "Between": "Entre",
        "CustomFilter": "Filtro personalizado",
        "CustomFilterPlaceHolder": "Insira um valor",
        "CustomFilterDatePlaceHolder": "Escolha uma data",
        "AND": "E",
        "OR": "Ou",
        "ShowRowsWhere": "Mostrar linhas onde:",
        "NotStartsWith": "Não começa com",
        "Like": "Como",
        "NotEndsWith": "Não termina com",
        "NotContains": "Não contém",
        "IsNull": "É nulo",
        "NotNull": "Não é nulo",
        "IsEmpty": "Está vazio",
        "IsNotEmpty": "Não está vazio",
        "AddCurrentSelection": "Adicionar seleção atual ao filtro",
        "UnGroupButton": "Clique aqui para desagrupar",
        "AutoFitAll": "Ajustar automaticamente todas as colunas",
        "AutoFit": "Ajustar automaticamente esta coluna",
        "Clear": "Limpar",
        "FilterMenuDialogARIA": "Menu de diálogo de filtro",
        "ExcelFilterDialogARIA": "Diálogo de filtro do Excel",
        "DialogEditARIA": "Editar diálogo",
        "ColumnChooserDialogARIA": "Seletor de coluna",
        "ColumnMenuDialogARIA": "Menu de diálogo da coluna",
        "CustomFilterDialogARIA": "Diálogo de filtro personalizado",
        "SortAtoZ": "Ordenar de A a Z",
        "SortZtoA": "Ordenar de Z a A",
        "SortByOldest": "Ordenar por mais antigos",
        "SortByNewest": "Ordenar por mais novos",
        "SortSmallestToLargest": "Ordenar do menor para o maior",
        "SortLargestToSmallest": "Ordenar do maior para o menor",
        "Sort": "Ordenar",
        "FilterDescription": "Pressione a tecla Alt + seta para baixo para abrir o menu de filtro",
        "SortDescription": "Pressione Enter para classificar",
        "ColumnMenuDescription": "Pressione Alt + seta para baixo para abrir o menu da coluna",
        "GroupDescription": "Pressione Ctrl + espaço para agrupar",
        "ColumnHeader": "Cabeçalho de coluna",
        "TemplateCell": " é uma célula de modelo",
        "CommandColumnAria": "é o cabeçalho de coluna da coluna de comando",
        "DialogEdit": "Editar diálogo",
        "ClipBoard": "Área de transferência",
        "GroupButton": "Botão de grupo",
        "UnGroupAria": "Botão para desagrupar",
        "GroupSeperator": "Separador de grupo de colunas",
        "UnGroupIcon": "Desagrupar ícone da coluna agrupada",
        "GroupedSortIcon": "Ordenar ícone da coluna agrupada",
        "GroupedDrag": "Arraste a coluna agrupada",
        "GroupCaption": " é uma célula de legenda de grupo",
        "CheckBoxLabel": "Caixa de seleção",
        "Expanded": "Expandido",
        "Collapsed": "Recolhido"
      },
      "pager": {
        "currentPageInfo": "{0} de {1} páginas",
        "totalItemsInfo": "({0} registros)",
        "firstPageTooltip": "Ir para a primeira página",
        "lastPageTooltip": "Ir para a última página",
        "nextPageTooltip": "Ir para a próxima página",
        "previousPageTooltip": "Ir para a página anterior",
        "nextPagerTooltip": "Ir para os próximos itens do paginador",
        "previousPagerTooltip": "Ir para os itens do paginador anteriores",
        "pagerDropDown": "Registros por página",
        "pagerAllDropDown": "Registros",
        "All": "Todos",
        "totalItemInfo": "({0} registro)",
        "Container": "Contêiner de paginador",
        "Information": "Informações de paginador",
        "ExternalMsg": "Mensagem externa de paginador",
        "Page": "Página",
        "Of": " de ",
        "Pages": " páginas"
      }
    }
}
  

export function initSyncfusion() {
    registerLicense('Ngo9BigBOggjHTQxAR8/V1NBaF5cWWFCf1FpRmJGdld5fUVHYVZUTXxaS00DNHVRdkdnWXpec3VQQ2NfUkJ+X0c=');
    L10n.load(locale);
}