version: '3.5'

services:
  app_cidadao:
    image: postgres
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-docker}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-docker}
      POSTGRES_DB: ${POSTGRES_DB:-app_cidadao}
  app_cidadao_test:
    image: postgres
    ports:
      - 5436:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-docker}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-docker}
      POSTGRES_DB: ${POSTGRES_DB:-app_cidadao_test}